<?php
	include 'includes/session.php';
    if(isset($_GET['return'])){
		$return = $_GET['return'];
		
	}
	else{
		$return = 'marriage.php';
	}

	if(isset($_POST['submit'])){			
		$RECORD_NO    	=$_POST['RECORD_NO'];
		$LICENSE_NO     	=$_POST['LICENSE_NO'];
        $NAME_MALE  	=$_POST['NAME_MALE'];
        $NAME_FEMALE   	=$_POST['NAME_FEMALE'];
		$LEGAL_STATUS_MALE		=$_POST['LEGAL_STATUS_MALE'];
        $LEGAL_STATUS_FEMALE    	=$_POST['LEGAL_STATUS_FEMALE'];
        $ACTUAL_ADDRESS_MALE      =$_POST['ACTUAL_ADDRESS_MALE'];
        $ACTUAL_ADDRESS_FEMALE      =$_POST['ACTUAL_ADDRESS_FEMALE'];
        $DATE_OF_BIRTH_MALE   =$_POST['DATE_OF_BIRTH_MALE'];
        $DATE_OF_BIRTH_FEMALE    =$_POST['DATE_OF_BIRTH_FEMALE'];
		$POB_MALE   			 =$_POST['POB_MALE'];
		$POB_FEMALE    =$_POST['POB_FEMALE'];
		$DATE_BAPTISM_MALE    =$_POST['DATE_BAPTISM_MALE'];
        $DATE_BAPTISM_FEMALE    	=$_POST['DATE_BAPTISM_FEMALE'];
        $PLACE_BAPTISM_MALE      =$_POST['PLACE_BAPTISM_MALE'];
        $PLACE_BAPTISM_FEMALE      =$_POST['PLACE_BAPTISM_FEMALE'];
        $PARENTS_MALE   =$_POST['PARENTS_MALE'];
        $PARENTS_FEMALE    =$_POST['PARENTS_FEMALE'];
		$SPONSORS_MALE   			 =$_POST['SPONSORS_MALE'];
		$SPONSORS_FEMALE    =$_POST['SPONSORS_FEMALE'];
		$MARRIAGE_MINISTER    =$_POST['MARRIAGE_MINISTER'];
		$DATE_OF_MARRIAGE    =$_POST['DATE_OF_MARRIAGE'];
		$BOOK_NO    		=$_POST['BOOK_NO'];
		$PAGE_NO    		=$_POST['PAGE_NO'];
		$REG_NO    			=$_POST['REG_NO'];
		$SERIES_NO    		=$_POST['SERIES_NO'];
		$NOTATIONS    		=$_POST['NOTATIONS'];

		// $sql = "SELECT * FROM tbl_marriage WHERE RECORD_NO = '$RECORD_NO' OR LICENSE_NO='$LICENSE_NO'";
		// $query = $conn->query($sql);
		// if($query->num_rows > 0){
			// $_SESSION['error'] = "RECORD_NO already exist! or LICENSE NO Make sure the number are unique";
		// }else{
			// $sql= "INSERT INTO `tbl_marriage`(`RECORD_NO`, `LICENSE_NO`, `NAME_MALE`, `NAME_FEMALE`, `LEGAL_STATUS_MALE`, `LEGAL_STATUS_FEMALE`, `ACTUAL_ADDRESS_MALE`, `ACTUAL_ADDRESS_FEMALE`, `DATE_OF_BIRTH_MALE`, `DATE_OF_BIRTH_FEMALE`, `POB_MALE`, `POB_FEMALE`, `DATE_BAPTISM_MALE`, `DATE_BAPTISM_FEMALE`, `PLACE_BAPTISM_MALE`, `PLACE_BAPTISM_FEMALE`, `PARENTS_MALE`, `PARENTS_FEMALE`, `SPONSORS_MALE`, `SPONSORS_FEMALE`, `MARRIAGE_MINISTER`, `DATE_OF_MARRIAGE`,`SERIES_NO`,`BOOK_NO`,`PAGE_NO`,`REG_NO`,`NOTATIONS`) 
			// VALUES ('$RECORD_NO','$LICENSE_NO','$NAME_MALE','$NAME_FEMALE','$LEGAL_STATUS_MALE','$LEGAL_STATUS_FEMALE','$ACTUAL_ADDRESS_MALE','$ACTUAL_ADDRESS_FEMALE','$DATE_OF_BIRTH_MALE','$DATE_OF_BIRTH_FEMALE','$POB_MALE','$POB_FEMALE','$DATE_BAPTISM_MALE','$DATE_BAPTISM_FEMALE','$PLACE_BAPTISM_MALE','$PLACE_BAPTISM_FEMALE','$PARENTS_MALE','$PARENTS_FEMALE','$SPONSORS_MALE','$SPONSORS_FEMALE','$MARRIAGE_MINISTER','$DATE_OF_MARRIAGE','$SERIES_NO','$BOOK_NO','$PAGE_NO','$REG_NO','$NOTATIONS')";
			// if($conn->query($sql)){
				// $_SESSION['success'] = 'New record have been created.';
			// }
			// else{
				// $_SESSION['error'] = $conn->error;
			// }
		// }
		
		 $sql= "INSERT INTO `tbl_marriage`(`RECORD_NO`, `LICENSE_NO`, `NAME_MALE`, `NAME_FEMALE`, `LEGAL_STATUS_MALE`, `LEGAL_STATUS_FEMALE`, `ACTUAL_ADDRESS_MALE`, `ACTUAL_ADDRESS_FEMALE`, `DATE_OF_BIRTH_MALE`, `DATE_OF_BIRTH_FEMALE`, `POB_MALE`, `POB_FEMALE`, `DATE_BAPTISM_MALE`, `DATE_BAPTISM_FEMALE`, `PLACE_BAPTISM_MALE`, `PLACE_BAPTISM_FEMALE`, `PARENTS_MALE`, `PARENTS_FEMALE`, `SPONSORS_MALE`, `SPONSORS_FEMALE`, `MARRIAGE_MINISTER`, `DATE_OF_MARRIAGE`,`SERIES_NO`,`BOOK_NO`,`PAGE_NO`,`REG_NO`,`NOTATIONS`) 
			VALUES ('$RECORD_NO','$LICENSE_NO','$NAME_MALE','$NAME_FEMALE','$LEGAL_STATUS_MALE','$LEGAL_STATUS_FEMALE','$ACTUAL_ADDRESS_MALE','$ACTUAL_ADDRESS_FEMALE','$DATE_OF_BIRTH_MALE','$DATE_OF_BIRTH_FEMALE','$POB_MALE','$POB_FEMALE','$DATE_BAPTISM_MALE','$DATE_BAPTISM_FEMALE','$PLACE_BAPTISM_MALE','$PLACE_BAPTISM_FEMALE','$PARENTS_MALE','$PARENTS_FEMALE','$SPONSORS_MALE','$SPONSORS_FEMALE','$MARRIAGE_MINISTER','$DATE_OF_MARRIAGE','$SERIES_NO','$BOOK_NO','$PAGE_NO','$REG_NO','$NOTATIONS')";
			if($conn->query($sql)){
				$_SESSION['success'] = 'New record have been created.';
        audit_log($conn,$user,'Marriage Added',"Record No: $RECORD_NO - $NAME_MALE & $NAME_FEMALE");
			}
			else{
				$_SESSION['error'] = $conn->error;
			}
	

	}	
	else{
		$_SESSION['error'] = 'Fill up add form first';
		
	}
	//header('location: clientAccount.php?q='.$_POST['id']);
	header('location:'.$return);
?>
